# Generated by Django 2.1.5 on 2021-07-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
