# Generated by Django 2.1.5 on 2021-07-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_like_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_amount',
        ),
    ]
